version: '3.9'

services:
  api_banco:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017
    volumes:
      - .:/api_banco
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - banco_net

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - banco_net

volumes:
  mongo_data:

networks:
  banco_net:
